### ISSUE TITLE
No handler for message if the message haven't x-message-type header and configuration contains more then one subscription.

### ISSUE THREAD

**Issue by BlackBred** [SDVentures/Contour#55]
If a message haven't x-message-type header then will not find a handler for this message.
An exception will be thrown "No handler for message labeled [] on queue [test.queue]."

The handler will be found if there is a single subscription only. The reason is the legacy code.
  // NOTE: this is needed for compatibility with v1 of ServiceBus
  if (this.consumers.Count == 1)
  {
          consumingAction = this.consumers.Values.Single();
   }

**Comment by semion-akimtsev** [comment]
Will be fixed in https://github.com/SDVentures/Contour/pull/53
