### ISSUE TITLE
Incorrect sender configuration logging.

### ISSUE THREAD

**Issue by BlackBred** [SDVentures/Contour#56]
The BusConfiguration class contains logging code:
Logger.Trace(m => m("Вызван метод для валидации конфигурации. Строка соединия - [{0}], адрес конечной точки - [{1}], получаемые сообщения - [{2}], отправляемые сообщения - [{3}]", this.ConnectionString, this.Endpoint, this.ReceiverConfigurations != null ? string.Join(";", this.ReceiverConfigurations.Select(x => x.Label)) : "null", this.SenderConfigurations != null ? **string.Join(";", this.SenderConfigurations)** : "null"));

It is not correct. Need to write labels: this.SenderConfigurations.Select(x => x.Label)

**Comment by semion-akimtsev** [comment]
Will be fixed in https://github.com/SDVentures/Contour/pull/53
